### ISSUE TITLE
Feature downstream dependency mapping

### ISSUE THREAD

**Issue by pinkforest** [RustCrypto/rustls-rustcrypto#34]
Many upstream dependencies come with default features causing std brought in and other potentially unwanted features

Sorting these rn

**Comment by pinkforest** [comment]
This was sorted via
- #43

**Comment by evanrichter** [comment]
this kind of work is so tedious yet much appreciated, thank you! <3

**Comment by pinkforest** [comment]
tyvm word like these means a lot :) I secretly love yak tuning these features :blush:
