### ISSUE TITLE
`no_std` gating - gate-in `alloc`

### ISSUE THREAD

**Issue by pinkforest** [RustCrypto/rustls-rustcrypto#36]
There are feature gates for `std` that could be under `alloc` perhaps ? e.g. 

```
#[cfg(not(feature = "std"))]
use alloc::boxed::Box;
use alloc::format;
use alloc::sync::Arc;
use core::marker::PhantomData;
```

Trouble is current rustls largely needs alloc - nonetheless

We could have all `alloc` gated as feature as there is talk of having `Arc-less` version that doesn't require Alloc ?

**Comment by newpavlov** [comment]
Yes, these should be under the `alloc` feature. We could leave stub like this for the time being:
```rust
#[cfg(not(feature = "alloc"))]
compile_error!("Rustls currently does not support alloc-less environments");

```

**Comment by Taowyoo** [comment]
Willing to take this.
I think the PR just need to update feature gate on those `::alloc` imports.
