### ISSUE TITLE
API for providing Rng

### ISSUE THREAD

**Issue by pinkforest** [RustCrypto/rustls-rustcrypto#41]
Currently there is `GenericRandomSigner` that plugs to `rand_core::OsRng` that requires `getrandom`

We'll need idiomatic API here to plug into provided Rng vs supplying one from here

**Comment by tarcieri** [comment]
Related:

- https://github.com/RustCrypto/meta/issues/19
- https://github.com/RustCrypto/traits/pull/1371

**Comment by pinkforest** [comment]
I looked into this and `Send + Sync` being required everywhere makes things interesting with self-mutable csprng.

In addition X25519 via [rustls::CryptoProvider](https://docs.rs/rustls/latest/rustls/crypto/struct.CryptoProvider.html) doesn't get the [the provided](https://github.com/RustCrypto/rustls-rustcrypto/blob/master/src/lib.rs#L30) impl for [rustls::SecureRandom](https://docs.rs/rustls/latest/rustls/crypto/trait.SecureRandom.html) by design -

As the [underlying crypto primitive library is supposed](https://docs.rs/rustls/latest/rustls/crypto/trait.SecureRandom.html#tymethod.fill) to provide it from within the crypto primitive library itself.

e.g. [src/kx/x25519#L19](https://github.com/RustCrypto/rustls-rustcrypto/blob/master/src/kx.rs#L17) uses `x25519_dalek::EphemeralSecret::random_from_rng(rand_core::OsRng);`

Question is how do we relay / get the csprng impl to e.g. kx x25519 as above without creating other trouble.

Effectively we need it to be `x25519_dalek::EphemeralSecret::random_from_rng(relay_csprng);`

Now we cannot relay directly that `relay_csprng` here since rustls is the one that calls the relevant crypto primitive implementation and where the relayed mutable csprng would have to come from a stored state given we are not calling it.

Using self-mutable impl would require creating a holder-struct somewhere leading to all sorts of complications navigating the Arc<RwLock|Mutex<_>> landscape and spinlock/lock-free stuff given both the [RngCore](https://rust-random.github.io/rand/rand_core/trait.RngCore.html) and the provided [SecureRandom](https://docs.rs/rustls/latest/rustls/crypto/trait.SecureRandom.html) are self-mutable

Or hardcoding the used RngCore impl (OsRng) into `CryptoProvider` as is done now everywhere.

What kind of interface if any would be possible that doesn't involve keeping state in the middle given the integration ?

Given dalek expects Rng to be supplied to itself - cannot supply this to it without keeping state in the middle.

Doing this via features would lead to same trouble as was with dalek backend selection and rng is mutually-exclusive cfg.

**Comment by pinkforest** [comment]
@ctz Hi - Would you have any ideas how to navigate the dilemma here ?

The crypto primitives have started to adopt construction with random_from_rng(&mut rng) e.g. [x25519-dalek::EphemeralSecret](https://github.com/dalek-cryptography/curve25519-dalek/blob/main/x25519-dalek/src/x25519.rs#L94)

This is different to rustls which expects cryptography primitive to supply it's own rng unlike the above.

Would rustls be open to either support [rand_core::CryptoRng](https://rust-random.github.io/rand/rand_core/trait.CryptoRng.html) or at least the ability to pass [rustls::SecureRandom](https://docs.rs/rustls/latest/rustls/crypto/trait.SecureRandom.html) to lower level primitives which expect something like it ?

Otherwise people would need to effectively write their own providers with their given provider of randomness separately leading to endless permutations of `CryptoProvider` which may not be always maintained etc.

I see downstream need for wasm, embedded and host rand which would pass their own implemented CryptoRng.

Note CryptoRng offers several methods over SecureRandom so preference would be rustls to adopt CryptoRng ?

**Comment by pinkforest** [comment]
Raised a feature request in rustls to support `rand_core::CryptoRng`
- https://github.com/rustls/rustls/issues/1853

**Comment by pinkforest** [comment]
We can't really do anything here given rustls doesn't want to support it so closing this issue.

However we can document the mechanism how to override getrandom with custom instead to describe no_std compatbility.

Superceded by
- #56
