### ISSUE TITLE
rustls is not enabled for dependabot

### ISSUE THREAD

**Issue by stevefan1999-personal** [RustCrypto/rustls-rustcrypto#80]
As of right now, rustls released [0.23.10](https://github.com/rustls/rustls/releases/tag/v%2F0.23.10) but we are still staggering in 0.23.0. Despite the API changes shouldn't be that breaking, it is always good to keep an eye out of the latest release and let CI do its thing.

**Comment by pinkforest** [comment]
It gets automatically 0.23.10 as it's SemVer compatible there is no need to bump given it's not pinned.

Typically binaries only do locked builds and even then it needs to explicitly add --locked to build as non-locked is default.

Typically pinning libraries isn't advisable as it can cause duplicates in dep tree.

**Comment by pinkforest** [comment]
Actually checking dependabot is in fact enabled.. it seems to not upgrade it for some reason

This seems to be dependabot issue

**Comment by pinkforest** [comment]
Oh it's been ignored for 0.23:
https://github.com/RustCrypto/rustls-rustcrypto/pull/23

**Comment by tarcieri** [comment]
It turns out it's hard to un-ignore a dependency with dependabot: https://github.com/dependabot/dependabot-core/issues/1384

But I can try...

**Comment by tarcieri** [comment]
Okay, #82 is open, although I'm not sure why it wen to `0.23.7` instead of `0.23.10`. Perhaps there's some other dependency incompatibility.

Anyway, closing this.
